### PR TITLE
FAQs added

### LINKED ISSUE #95: ReadMe: Add FAQ Section
**I was looking forward to add FAQs Section in the ReadMe file.**

### PR DESCRIPTION
**Pull request by dudenayak**
Fixed #95

### CODE REVIEW

**Comment by praveenscience** [comment]
Can you please set your formatter not to change the `*` to `-`? Coz we're using CommonMark and other restrictions here. 😊

**Review by praveenscience — CHANGES_REQUESTED** [review]
Can you please set your formatter not to change the `*` to `-`? Coz we're using CommonMark and other restrictions here. 😊

**Comment by dudenayak** [comment]
> Can you please set your formatter not to change the `*` to `-`? Coz we're using CommonMark and other restrictions here. 😊

Okay sure

**Comment by dudenayak** [comment]
Fixed symbol issue. Please check.

**Comment by praveenscience** [comment]
@dudenayak I meant the `*` to `-`. See [changes section](https://github.com/praveenscience/Internship-LMS-FrontEnd/pull/98/files) and you will understand.

**Comment by dudenayak** [comment]
> @dudenayak I meant the `*` to `-`. See [changes section](https://github.com/praveenscience/Internship-LMS-FrontEnd/pull/98/files) and you will understand.

But I've already changed it.

**Review by dudenayak — COMMENTED** [review]
Please check this once again there are no ' * ' here.

**Comment by dudenayak** [comment]
I've made the changes that you asked. Please check and tell me if any other changes are required.

**Pull request merged**
