### PR TITLE
Add contributing.md with all necessary contributing guidelines.

### PR DESCRIPTION
**Pull request by tejan-singh**
### Describe the changes you've made

add contributing.md and updated readme file.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by praveenscience** [comment]
This is being done by Deeksha. 😊

**Comment by praveenscience** [comment]
Cool, let me review. LoL.

**Comment by tejan-singh** [comment]
@praveenscience. This is for contribution guidelines. Very Necessary. Please review and merge

**Comment by praveenscience** [comment]
Merged manually! ✋🏻

**Pull request closed without merging**
