### PR TITLE
Contributing.md added

### LINKED ISSUE #3: Create a Contributing Readme file similar to Rezume project!
I had created something like this before: [Contributing · CatsInTech/Rezume](https://github.com/CatsInTech/Rezume/blob/master/CONTRIBUTING.md).

I want someone to use their creative ideas to create a similar one to this project. We do have a [video](https://youtu.be/GaosMNyPKZc?list=PLO_Y0rsm7b3Yc8FtNhCuD5TO0QM8CnTZj) of the same too! 😁

Make it awwwwesome!

### PR DESCRIPTION
**Pull request by vismitap**
Fixes #3

## Related Issue 

- Contributing.md is added for this repository which is similar to Rezume project.

Closes: #3 

### Describe the changes you've made

A new contributing.md file is added.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
 
image

### CODE REVIEW

**Comment by praveenscience** [comment]
We need pics... Let's add them and we'll get this merged? 😁

**Comment by vismitap** [comment]
> We need pics... Let's add them and we'll get this merged? 😁

Yes, sure! When will you be able to provide the pics? I will quickly add them ✨

**Comment by praveenscience** [comment]
Ahhh, we had a plan to do it together. Since we don't, let me send you the pics ASAP! 😅

**Comment by vismitap** [comment]
> Ahhh, we had a plan to do it together. Since we don't, let me send you the pics ASAP! 😅

Yes, please! 😅

**Comment by vismitap** [comment]
Please add the SWoC and difficulty level labels!

**Pull request merged**
