### PR TITLE
Techstackissue 49

### PR DESCRIPTION
**Pull request by starrohan999**
## Related Issue 

Tech Stack poster is updated as per changes.

Closes: #[49]

## Type of change
final result:
Purple, White and Orange Modern Discoveries Science   Technology YouTube Video Outro

### CODE REVIEW

**Comment by starrohan999** [comment]
SIR @praveenscience  check this.

**Comment by praveenscience** [comment]
Please refrain from creating multiple PRs for the same issue. Closing this as a dupe of #50.

**Comment by starrohan999** [comment]
sir I am not understand

**Comment by praveenscience** [comment]
@starrohan999 Why did you create a new PR?

**Comment by starrohan999** [comment]
so what I can do now, please sir explain to me

**Comment by starrohan999** [comment]
can we do changes in the same pr?

**Comment by starrohan999** [comment]
sir you actually said that do some changes in #50 , so how can change it without a new pr.

**Comment by praveenscience** [comment]
@starrohan999 Didn't see this? 😊 
image

**Comment by starrohan999** [comment]
thank you so much i understand

first of all, do changes and then simply commit it in branch issue-49

**Comment by starrohan999** [comment]
am I right sir?

**Comment by praveenscience** [comment]
That's correct @starrohan999 😊

**Comment by starrohan999** [comment]
thank you so much you are the best mentor

**Comment by starrohan999** [comment]
i will do changes asap

**Pull request closed without merging**
