### PR TITLE
Fixes issue-49[tech stack poster]

### PR DESCRIPTION
**Pull request by starrohan999**
## Related Issue 

TECH STACK POSTER

Closes: #49

TECH STACK POSTER

### CODE REVIEW

**Comment by praveenscience** [comment]
Can we make it more better? Something in the lines of:

image

image

image

image

Let me know! 😊

**Review by praveenscience — CHANGES_REQUESTED** [review]
See above.

**Comment by starrohan999** [comment]
sir, please review it

**Comment by starrohan999** [comment]
sir @praveenscience  is this ok or not

**Comment by praveenscience** [comment]
Can we try not to add more in the PR, but please add the image here in the discussion? Once I say okay, just squash and push the PR. 😁

**Comment by starrohan999** [comment]
ok @praveenscience  sir

**Comment by praveenscience** [comment]
Yea, temporarily, let's close this off. Okay?

**Pull request closed without merging**
