### PR TITLE
Design-user 

### PR DESCRIPTION
**Pull request by Spring-dot**
## Related Issue 

- Info about the related issue 
 Designing basic wireframes for the website

Closes: #81 

### Describe the changes you've made

I have added a link to the design for user-related.

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Contains design link.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Comment by praveenscience** [comment]
Hey, @Spring-dot Can you also please upload a screenshot for people who don't have Balsamiq Accounts?

**Comment by Spring-dot** [comment]
ok, I will add screenshots.

**Comment by Spring-dot** [comment]
@praveenscience I have added screenshots, Please review.

**Comment by praveenscience** [comment]
Damn! Love your designs! 🔥
Check this out @Insomaniacgamer @ampsteric @tejan-singh @alphaX86

**Comment by alphaX86** [comment]
Yo the designs are sooo good 🔥🔥 well done @Spring-dot

**Comment by alphaX86** [comment]
But I have a suggestion though, why not keep the menu bar top at the landing page instead of bottom? Does it affect the UX if we do that? Just a doubt though

**Comment by Insomaniacgamer** [comment]
@Spring-dot AMAZING job, really loved it
@praveenscience let's move forward with this

**Comment by Spring-dot** [comment]
> But I have a suggestion though, why not keep the menu bar top at the landing page instead of bottom? Does it affect the UX if we do that? Just a doubt though

That I wanted to create as buttons (not exactly menu bar), We can keep at top, but since after reading about devternship, user will navigate through these options available so I kept after text part.

**Comment by praveenscience** [comment]
We can indeed request changes at a later stage. I would like to upgrade the severity to `Level2` if that's okay with everyone. This is indeed an awesome work done! 🔥

**Comment by alphaX86** [comment]
> > But I have a suggestion though, why not keep the menu bar top at the landing page instead of bottom? Does it affect the UX if we do that? Just a doubt though
> 
> That I wanted to create as buttons (not exactly menu bar), We can keep at top, but since after reading about devternship, user will navigate through these options available so I kept after text part.

Ok then. We'll proceed as such

**Review by alphaX86 — APPROVED** [review]
LGTM 👍 Good to Go! 🎉

**Review by praveenscience — APPROVED** [review]
👍

**Pull request merged**
